name: Destroy Infra and Lambda

on:
  workflow_dispatch:

jobs:
  destroy:
    name: Destroy Terraform Resources
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download terraform Artifacts
        uses: actions/download-artifact@v4
        with:
          name: terraform artifacts 
          path: terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init (with existing state)
        run: terraform -chdir=terraform init

      - name: Terraform Destroy
        run: terraform -chdir=terraform destroy -auto-approve

      - name: Clean up local terraform files
        run: |
          rm -rf terraform/.terraform
          rm -f terraform/.terraform.lock.hcl
          rm -f terraform/terraform.tfstate
          rm -f terraform/terraform.tfstate.backup
          rm -f terraform/tfplan 
